apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default-serviceaccount-secret-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: model-serving
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io