# Base image
FROM python:3.9.21-slim

# Set working directory
WORKDIR /app

# # Install libraries
RUN apt-get update && apt-get install -y \
    cmake \
    g++ \
    make \
    libgl1-mesa-glx \
    libglib2.0-0 \
    unzip \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --upgrade pip

# Copy and install dependencies
COPY requirements.txt /app

# RUN pip install --upgrade pip
RUN pip install --no-cache -r requirements.txt

# install pytorch with cpu
RUN pip3 install torch==2.6.0+cu126 torchvision==0.21.0+cu126 torchaudio==2.6.0+cu126 --index-url https://download.pytorch.org/whl/cpu

# install pytorch with cuda 126. Remember run --gpus all in CLI
# RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126