apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: kube-metrics
  labels:
    app: cadvisor
spec:
  selector:
    app.kubernetes.io/name: cadvisor
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
