apiVersion: v1
kind: Service
metadata:
  name: cadvisor
  namespace: kube-metrics
  labels:
    app: cadvisor
spec:
  type: LoadBalancer  # Hoặc NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: cadvisor
