- name: Create a Compute Engine instance
  hosts: localhost
  tasks:
    - name: Create a Compute Engine instance
      gcp_compute_instance:
        name: instance-1
        machine_type: e2-standard-8
        zone: us-central1-a
        project: jojogan-zombie
        auth_kind: serviceaccount
        service_account_file: ../secrets/jojogan-zombie-d30e04a80405.json
        state: present # Change to present to create the instance
        disks:
          - auto_delete: true
            boot: true
            initialize_params:
              source_image: projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20230727
              disk_size_gb: 20
        network_interfaces:
          - network:
              selfLink: global/networks/default
            access_configs:
              - name: External NAT
                type: ONE_TO_ONE_NAT

    - name: Create inbound firewall rule for port 8081, 8000 and 50000
      gcp_compute_firewall:
            name: allow-port-8081-50000-8000
            network:
              selfLink: global/networks/default
            allowed:
              - ip_protocol: TCP
                ports:
                  - 8081
                  - 8000
                  - 50000
            source_ranges:
              - 0.0.0.0/0 # Allow traffic from any source (use a more specific source range for security)
            direction: INGRESS # Direction from outside to inside, EGRESS is the opposite direction
            description: Port 8081 Jenkins, 50000 Jenkins, 8000 Zombie
            project: jojogan-zombie
            auth_kind: serviceaccount
            service_account_file: ../secrets/jojogan-zombie-d30e04a80405.json