apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: kube-metrics
  labels:
    app: prometheus-node-exporter
spec:
  selector:
    app.kubernetes.io/name: prometheus-node-exporter
  ports:
    - protocol: TCP
      port: 9100
      targetPort: 9100
